name: CakeHttp build and deploy

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    name: .NET 7 Build
    runs-on: ubuntu-latest

    steps:
    
    - name: Print GitHub context variables For Pull Request
      run: echo 'Branch => ${{ github.ref_name }}, Action => ${{ github.event_name }}'
      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test Test/CakeHttp.Tests.csproj --no-build --verbosity normal -c Release

  deploy:
    name: .NET 7 Deploy to Nuget package
    if: github.ref_name == 'dev' || github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x    
    - name: Pack
      run: dotnet pack DevEverywhere.CakeHttp/CakeHttp.csproj --verbosity normal -c Release
    - name: Publish to Nuget
      
      run: |
        package="$(find . -wholename '**/Release/*.nupkg' -exec echo "{}" \;)";

        if [[ ${BRANCH_NAME} = 'dev' ]]
          newPackageName="$(echo $package | sed 's/CakeHttp\./CakeHttp\.Dev\./')" ; mv $package $newPackageName ; package=$newPackageName ;

        dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json;
