name: CakeHttp build and deploy

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: .NET 7 Build

    runs-on: ubuntu-latest

    steps:
    
    - name: Print GitHub context variables For Pull Request
      run: echo 'Base Branch => ${{ github.github.base_ref }}, Branch => ${{ github.ref_name }}, Action => ${{ github.event_name }}'
      
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Print GitHub context variables
      run: echo 'Branch => ${{ github.ref_name }}, Action => ${{ github.event_name }}'

  deploy:
    name: .NET 7 Deploy to Nuget package
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
  
    steps:
    
    - name: Pack
      run: dotnet pack --no-build --verbosity normal -c '**/Release/*.nupkg

    - name: Publish to Nuget
      run: |
        package="$(find . -wholename '**/Release/*.nupkg' -exec echo "{}" \;)"
        echo $package
        dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
